name: Full Stack CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install backend
        run: |
          cd backend
          npm install

      - name: Run backend (optional)
        run: |
          cd backend
          npm run build --if-present

      # Frontend
      - name: Install frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build